// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: credentialservice.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace com.intercede.BluetoothSmartcard.Commands {

  /// <summary>Holder for reflection information generated from credentialservice.proto</summary>
  public static partial class CredentialserviceReflection {

    #region Descriptor
    /// <summary>File descriptor for credentialservice.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CredentialserviceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdjcmVkZW50aWFsc2VydmljZS5wcm90bxITYmx1ZXRvb3RoLnNtYXJ0Y2Fy",
            "ZBofZ29vZ2xlL3Byb3RvYnVmL3RpbWVzdGFtcC5wcm90bxoZZ29vZ2xlL3By",
            "b3RvYnVmL2FwaS5wcm90byJdChFDcmVkZW50aWFsUmVxdWVzdCJICghLZXlV",
            "c2FnZRIMCghOT19VU0FHRRAAEggKBFNJR04QARILCgdFTkNSWVBUEAISCgoG",
            "VkVSSUZZEAQSCwoHREVDUllQVBAIIjQKCkNyZWRlbnRpYWwSEgoKaWRlbnRp",
            "ZmllchgBIAEoDBISCgpjcmVkZW50aWFsGAIgASgMIkoKEkNyZWRlbnRpYWxS",
            "ZXNwb25zZRI0CgtjcmVkZW50aWFscxgBIAMoCzIfLmJsdWV0b290aC5zbWFy",
            "dGNhcmQuQ3JlZGVudGlhbCIlChBTaWduYXR1cmVSZXF1ZXN0EhEKCXBsYWlu",
            "dGV4dBgBIAEoDCImChFTaWduYXR1cmVSZXNwb25zZRIRCglzaWduYXR1cmUY",
            "ASABKAwy0gEKEUNyZWRlbnRpYWxTZXJ2aWNlEmIKD1JlYWRDcmVkZW50aWFs",
            "cxImLmJsdWV0b290aC5zbWFydGNhcmQuQ3JlZGVudGlhbFJlcXVlc3QaJy5i",
            "bHVldG9vdGguc21hcnRjYXJkLkNyZWRlbnRpYWxSZXNwb25zZRJZCghTaWdu",
            "RGF0YRIlLmJsdWV0b290aC5zbWFydGNhcmQuU2lnbmF0dXJlUmVxdWVzdBom",
            "LmJsdWV0b290aC5zbWFydGNhcmQuU2lnbmF0dXJlUmVzcG9uc2VCagopY29t",
            "LmludGVyY2VkZS5ibHVldG9vdGhzbWFydGNhcmQuY29tbWFuZHNCDlNpZ25E",
            "YXRhUHJvdG9zgAEBqgIpY29tLmludGVyY2VkZS5CbHVldG9vdGhTbWFydGNh",
            "cmQuQ29tbWFuZHNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.ApiReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::com.intercede.BluetoothSmartcard.Commands.CredentialRequest), global::com.intercede.BluetoothSmartcard.Commands.CredentialRequest.Parser, null, null, new[]{ typeof(global::com.intercede.BluetoothSmartcard.Commands.CredentialRequest.Types.KeyUsage) }, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::com.intercede.BluetoothSmartcard.Commands.Credential), global::com.intercede.BluetoothSmartcard.Commands.Credential.Parser, new[]{ "Identifier", "Credential_" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::com.intercede.BluetoothSmartcard.Commands.CredentialResponse), global::com.intercede.BluetoothSmartcard.Commands.CredentialResponse.Parser, new[]{ "Credentials" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::com.intercede.BluetoothSmartcard.Commands.SignatureRequest), global::com.intercede.BluetoothSmartcard.Commands.SignatureRequest.Parser, new[]{ "Plaintext" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::com.intercede.BluetoothSmartcard.Commands.SignatureResponse), global::com.intercede.BluetoothSmartcard.Commands.SignatureResponse.Parser, new[]{ "Signature" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class CredentialRequest : pb::IMessage<CredentialRequest> {
    private static readonly pb::MessageParser<CredentialRequest> _parser = new pb::MessageParser<CredentialRequest>(() => new CredentialRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CredentialRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::com.intercede.BluetoothSmartcard.Commands.CredentialserviceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CredentialRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CredentialRequest(CredentialRequest other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CredentialRequest Clone() {
      return new CredentialRequest(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CredentialRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CredentialRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CredentialRequest other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the CredentialRequest message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum KeyUsage {
        [pbr::OriginalName("NO_USAGE")] NoUsage = 0,
        [pbr::OriginalName("SIGN")] Sign = 1,
        [pbr::OriginalName("ENCRYPT")] Encrypt = 2,
        [pbr::OriginalName("VERIFY")] Verify = 4,
        [pbr::OriginalName("DECRYPT")] Decrypt = 8,
      }

    }
    #endregion

  }

  public sealed partial class Credential : pb::IMessage<Credential> {
    private static readonly pb::MessageParser<Credential> _parser = new pb::MessageParser<Credential>(() => new Credential());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Credential> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::com.intercede.BluetoothSmartcard.Commands.CredentialserviceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Credential() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Credential(Credential other) : this() {
      identifier_ = other.identifier_;
      credential_ = other.credential_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Credential Clone() {
      return new Credential(this);
    }

    /// <summary>Field number for the "identifier" field.</summary>
    public const int IdentifierFieldNumber = 1;
    private pb::ByteString identifier_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Identifier {
      get { return identifier_; }
      set {
        identifier_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "credential" field.</summary>
    public const int Credential_FieldNumber = 2;
    private pb::ByteString credential_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Credential_ {
      get { return credential_; }
      set {
        credential_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Credential);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Credential other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Identifier != other.Identifier) return false;
      if (Credential_ != other.Credential_) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Identifier.Length != 0) hash ^= Identifier.GetHashCode();
      if (Credential_.Length != 0) hash ^= Credential_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Identifier.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Identifier);
      }
      if (Credential_.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Credential_);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Identifier.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Identifier);
      }
      if (Credential_.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Credential_);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Credential other) {
      if (other == null) {
        return;
      }
      if (other.Identifier.Length != 0) {
        Identifier = other.Identifier;
      }
      if (other.Credential_.Length != 0) {
        Credential_ = other.Credential_;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Identifier = input.ReadBytes();
            break;
          }
          case 18: {
            Credential_ = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  public sealed partial class CredentialResponse : pb::IMessage<CredentialResponse> {
    private static readonly pb::MessageParser<CredentialResponse> _parser = new pb::MessageParser<CredentialResponse>(() => new CredentialResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CredentialResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::com.intercede.BluetoothSmartcard.Commands.CredentialserviceReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CredentialResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CredentialResponse(CredentialResponse other) : this() {
      credentials_ = other.credentials_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CredentialResponse Clone() {
      return new CredentialResponse(this);
    }

    /// <summary>Field number for the "credentials" field.</summary>
    public const int CredentialsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::com.intercede.BluetoothSmartcard.Commands.Credential> _repeated_credentials_codec
        = pb::FieldCodec.ForMessage(10, global::com.intercede.BluetoothSmartcard.Commands.Credential.Parser);
    private readonly pbc::RepeatedField<global::com.intercede.BluetoothSmartcard.Commands.Credential> credentials_ = new pbc::RepeatedField<global::com.intercede.BluetoothSmartcard.Commands.Credential>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::com.intercede.BluetoothSmartcard.Commands.Credential> Credentials {
      get { return credentials_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CredentialResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CredentialResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!credentials_.Equals(other.credentials_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= credentials_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      credentials_.WriteTo(output, _repeated_credentials_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += credentials_.CalculateSize(_repeated_credentials_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CredentialResponse other) {
      if (other == null) {
        return;
      }
      credentials_.Add(other.credentials_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            credentials_.AddEntriesFrom(input, _repeated_credentials_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class SignatureRequest : pb::IMessage<SignatureRequest> {
    private static readonly pb::MessageParser<SignatureRequest> _parser = new pb::MessageParser<SignatureRequest>(() => new SignatureRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SignatureRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::com.intercede.BluetoothSmartcard.Commands.CredentialserviceReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SignatureRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SignatureRequest(SignatureRequest other) : this() {
      plaintext_ = other.plaintext_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SignatureRequest Clone() {
      return new SignatureRequest(this);
    }

    /// <summary>Field number for the "plaintext" field.</summary>
    public const int PlaintextFieldNumber = 1;
    private pb::ByteString plaintext_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Plaintext {
      get { return plaintext_; }
      set {
        plaintext_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SignatureRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SignatureRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Plaintext != other.Plaintext) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Plaintext.Length != 0) hash ^= Plaintext.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Plaintext.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Plaintext);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Plaintext.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Plaintext);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SignatureRequest other) {
      if (other == null) {
        return;
      }
      if (other.Plaintext.Length != 0) {
        Plaintext = other.Plaintext;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Plaintext = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  public sealed partial class SignatureResponse : pb::IMessage<SignatureResponse> {
    private static readonly pb::MessageParser<SignatureResponse> _parser = new pb::MessageParser<SignatureResponse>(() => new SignatureResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SignatureResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::com.intercede.BluetoothSmartcard.Commands.CredentialserviceReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SignatureResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SignatureResponse(SignatureResponse other) : this() {
      signature_ = other.signature_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SignatureResponse Clone() {
      return new SignatureResponse(this);
    }

    /// <summary>Field number for the "signature" field.</summary>
    public const int SignatureFieldNumber = 1;
    private pb::ByteString signature_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Signature {
      get { return signature_; }
      set {
        signature_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SignatureResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SignatureResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Signature != other.Signature) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Signature.Length != 0) hash ^= Signature.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Signature.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Signature);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Signature.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Signature);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SignatureResponse other) {
      if (other == null) {
        return;
      }
      if (other.Signature.Length != 0) {
        Signature = other.Signature;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Signature = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
